#!/bin/bash

versionkept=$(grep -Po '(?<=versionkept=).*' /etc/autopaccache.conf)
beforeRemoval=$(ls /var/cache/pacman/pkg/ | wc -l)

#keep most recent version
/usr/bin/paccache -rk$versionkept

#Remove all cached versions of uninstalled packages,
/usr/bin/paccache -ruk0
afterRemoval=$(ls /var/cache/pacman/pkg/ | wc -l)
echo "$((beforeRemoval-afterRemoval)) cached packages have been removed.
